services:
  - type: web
    name: College-Lost-Found-System-
    env: node
    buildCommand: cd server && npm install && npm run build && cd ../client && npm install && npm run build
    startCommand: cd server && npm run seed && node dist/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        value: super_secret_college_lost_found_jwt_key_2026
